name: Windows build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  visual-studio:
    runs-on: windows-2022
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Build x64 game
        run: msbuild Project/HoverVehicleGame.sln /m /p:Configuration=${{ matrix.configuration }} /p:Platform=x64
